import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class frmSignUp extends javax.swing.JFrame {
    String signUpId;
    String mob;
    int length =10;
    String con;
    String pwd;
    Connection conn = null;
    Statement stat = null;
    ResultSet rest = null;
    String uid = "root", pass = "tiger";

    /**
     * Creates new form frmSignUp
     */
    public frmSignUp() {
        initComponents();
        txtSignUpPassword.setEchoChar('\u25cf');
        btnSignUpEye.setEnabled(false);
        txtCoinfirm.setEchoChar('\u25cf');
        btnCoinfirmEye.setEnabled(false);

        txtFirstName.setBackground(new Color(0, 0, 0, 204));
        txtLastName.setBackground(new Color(0, 0, 0, 204));
        txtSignUpEmailId.setBackground(new Color(0, 0, 0, 204));
        txtMobile.setBackground(new Color(0, 0, 0, 204));
        try {
            Class.forName("java.sql.Driver");
            //System.out.println("Driver Registered");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/library", uid, pass);
            //System.out.println("Connection Establish");
            stat = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rest=stat.executeQuery("select * from t;");
            //rest=stat.executeQuery("select *from dept;");
            //System.out.println("Ready For Query");

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Driver Not Found");
            System.exit(0);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Connection Not Establish" + e.getMessage());
            System.exit(0);
        }
        
        
    }
    public static boolean mobLengthCheck(String mob, int len) {
        return mob.length() == len;
    }
    public static boolean pwdValueCheck(String pwd) {
        if(pwd.length() >8){
            return true; 
        }
        else{
            return false;
        }
    }

    public static boolean checkPass(String pwd){
        boolean hasNum=false,hasUpper=false,hasLower=false,stat=false; char c;
        for(int i=0; i<pwd.length();i++){
            c=pwd.charAt(i);
            if(Character.isDigit(c)){
                hasNum=true;
            }
            if(Character.isUpperCase(c)){
                hasUpper=true;
            }
            if(Character.isLowerCase(c)){
                hasLower=true;
            }
        }
        if(hasNum && hasUpper && hasLower){
            stat=true;
        }
        return stat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgImageSignUp = new javax.swing.JPanel();
        fgImageSignUp = new javax.swing.JPanel();
        txtLastName = new javax.swing.JTextField();
        txtSignUpEmailId = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSignUpPassPanel = new javax.swing.JPanel();
        txtSignUpPassword = new javax.swing.JPasswordField();
        btnSignUpEye = new javax.swing.JButton();
        txtCoinfirmPanel = new javax.swing.JPanel();
        txtCoinfirm = new javax.swing.JPasswordField();
        btnCoinfirmEye = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblImageSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgImageSignUp.setMinimumSize(new java.awt.Dimension(0, 0));
        bgImageSignUp.setOpaque(false);
        bgImageSignUp.setPreferredSize(new java.awt.Dimension(1, 1));
        bgImageSignUp.setLayout(new java.awt.GridBagLayout());

        fgImageSignUp.setMinimumSize(new java.awt.Dimension(0, 0));
        fgImageSignUp.setOpaque(false);
        fgImageSignUp.setPreferredSize(new java.awt.Dimension(11, 11));

        txtLastName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(204, 0, 204));

        txtSignUpEmailId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSignUpEmailId.setForeground(new java.awt.Color(0, 255, 255));
        txtSignUpEmailId.setToolTipText("");
        txtSignUpEmailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSignUpEmailIdFocusLost(evt);
            }
        });

        txtFirstName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(51, 51, 255));

        txtMobile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(102, 255, 102));
        txtMobile.setToolTipText("Character Limit ! Not More Than  10 Digit");
        txtMobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMobileFocusLost(evt);
            }
        });
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rod Transparent", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("FIRST NAME:");

        jLabel3.setFont(new java.awt.Font("Rod Transparent", 1, 50)); // NOI18N
        jLabel3.setForeground(java.awt.Color.cyan);
        jLabel3.setText("EMAIL ID:");

        jLabel4.setFont(new java.awt.Font("Rod Transparent", 1, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("LAST NAME:");

        jLabel5.setFont(new java.awt.Font("Rod Transparent", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("MOBILE NO:");

        jLabel6.setFont(new java.awt.Font("Rod Transparent", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("PASSWORD:");

        jLabel7.setFont(new java.awt.Font("Rod Transparent", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("COINFIRM PASSWORD:");

        txtSignUpPassPanel.setBackground(new java.awt.Color(255, 255, 255));
        txtSignUpPassPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSignUpPassPanel.setPreferredSize(new java.awt.Dimension(376, 41));

        txtSignUpPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSignUpPassword.setForeground(java.awt.Color.orange);
        txtSignUpPassword.setBorder(null);
        txtSignUpPassword.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSignUpPasswordCaretUpdate(evt);
            }
        });
        txtSignUpPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSignUpPasswordFocusLost(evt);
            }
        });

        btnSignUpEye.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUpEye.setBorder(null);
        btnSignUpEye.setBorderPainted(false);
        btnSignUpEye.setContentAreaFilled(false);
        btnSignUpEye.setOpaque(true);
        btnSignUpEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSignUpEyeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSignUpEyeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout txtSignUpPassPanelLayout = new javax.swing.GroupLayout(txtSignUpPassPanel);
        txtSignUpPassPanel.setLayout(txtSignUpPassPanelLayout);
        txtSignUpPassPanelLayout.setHorizontalGroup(
            txtSignUpPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtSignUpPassPanelLayout.createSequentialGroup()
                .addComponent(txtSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignUpEye, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtSignUpPassPanelLayout.setVerticalGroup(
            txtSignUpPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSignUpPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
            .addComponent(btnSignUpEye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtCoinfirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        txtCoinfirmPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCoinfirm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCoinfirm.setForeground(new java.awt.Color(255, 0, 51));
        txtCoinfirm.setBorder(null);
        txtCoinfirm.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCoinfirmCaretUpdate(evt);
            }
        });
        txtCoinfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCoinfirmFocusLost(evt);
            }
        });

        btnCoinfirmEye.setBackground(new java.awt.Color(255, 255, 255));
        btnCoinfirmEye.setBorder(null);
        btnCoinfirmEye.setBorderPainted(false);
        btnCoinfirmEye.setContentAreaFilled(false);
        btnCoinfirmEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCoinfirmEyeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCoinfirmEyeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout txtCoinfirmPanelLayout = new javax.swing.GroupLayout(txtCoinfirmPanel);
        txtCoinfirmPanel.setLayout(txtCoinfirmPanelLayout);
        txtCoinfirmPanelLayout.setHorizontalGroup(
            txtCoinfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCoinfirmPanelLayout.createSequentialGroup()
                .addComponent(txtCoinfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(btnCoinfirmEye, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtCoinfirmPanelLayout.setVerticalGroup(
            txtCoinfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCoinfirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtCoinfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCoinfirmEye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI Semilight", 1, 50)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(153, 153, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fgImageSignUpLayout = new javax.swing.GroupLayout(fgImageSignUp);
        fgImageSignUp.setLayout(fgImageSignUpLayout);
        fgImageSignUpLayout.setHorizontalGroup(
            fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fgImageSignUpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCoinfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSignUpPassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(fgImageSignUpLayout.createSequentialGroup()
                .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fgImageSignUpLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(fgImageSignUpLayout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(btnSubmit)))
                .addContainerGap(512, Short.MAX_VALUE))
            .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fgImageSignUpLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fgImageSignUpLayout.createSequentialGroup()
                            .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(fgImageSignUpLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(166, 166, 166)
                            .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSignUpEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)))
                        .addGroup(fgImageSignUpLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        fgImageSignUpLayout.setVerticalGroup(
            fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fgImageSignUpLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(txtSignUpPassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtCoinfirmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnSubmit)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fgImageSignUpLayout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fgImageSignUpLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel4)
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fgImageSignUpLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)))
                    .addGroup(fgImageSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(txtSignUpEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51)
                    .addComponent(jLabel6)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel7)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        bgImageSignUp.add(fgImageSignUp, gridBagConstraints);

        lblImageSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo8.jpg"))); // NOI18N
        lblImageSignUp.setMinimumSize(new java.awt.Dimension(0, 0));
        lblImageSignUp.setPreferredSize(new java.awt.Dimension(1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        bgImageSignUp.add(lblImageSignUp, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgImageSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgImageSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSignUpEmailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSignUpEmailIdFocusLost
        signUpId = new String(txtSignUpEmailId.getText());
        if ((signUpId.indexOf("@") == -1) || (!signUpId.endsWith(".com") && (!signUpId.endsWith(".co.in")))) {
            JOptionPane.showMessageDialog(this, "Invalid Email Id...", "Error", 0);
            txtSignUpEmailId.requestFocus();
        }
    }//GEN-LAST:event_txtSignUpEmailIdFocusLost

    private void txtMobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileFocusLost
        mob = new String(txtMobile.getText());
        if (mobLengthCheck(mob, length)) {
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Entry...", "Error", 0);
            txtMobile.requestFocus();
        }
    }//GEN-LAST:event_txtMobileFocusLost

    private void txtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyTyped
        if (!(evt.getKeyChar() >= KeyEvent.VK_0 && evt.getKeyChar() <= KeyEvent.VK_9)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMobileKeyTyped

    private void txtSignUpPasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSignUpPasswordCaretUpdate
        con = new String(txtSignUpPassword.getPassword());
        btnSignUpEye.setEnabled(true);
        btnSignUpEye.setIcon(new ImageIcon("src/Eye11.png"));
        if (con.isEmpty()) {
            btnSignUpEye.setIcon(null);
            btnSignUpEye.setEnabled(false);
        }
    }//GEN-LAST:event_txtSignUpPasswordCaretUpdate

    private void btnSignUpEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpEyeMousePressed
        if (btnSignUpEye.isEnabled()) {
            //System.out.println("Button Pressed...");
            con = new String(txtSignUpPassword.getPassword());
            txtSignUpPassword.setEchoChar((char) 0);
            txtSignUpPassword.setText(con);
            btnSignUpEye.setIcon(new ImageIcon("src/Eye12.png"));
        }
    }//GEN-LAST:event_btnSignUpEyeMousePressed

    private void btnSignUpEyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpEyeMouseReleased
        if (btnSignUpEye.isEnabled()) {
            //System.out.println("Button Released...");
            btnSignUpEye.setIcon(new ImageIcon("src/Eye11.png"));
            txtSignUpPassword.setEchoChar('\u25cf');
            txtSignUpPassword.setText(con);
        }
    }//GEN-LAST:event_btnSignUpEyeMouseReleased

    private void txtSignUpPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSignUpPasswordFocusLost
        if(pwdValueCheck(con)){
            if(checkPass(con)){}
            else{
                JOptionPane.showMessageDialog(this,"Invalid Entry ,Please Write Atleast One Digit , Uppercase & LowerCase ","Error",0);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Too Small","Error",0);
        }
        if(btnSignUpEye.isEnabled()) {
            //System.out.println("Button Released...");
            btnSignUpEye.setIcon(new ImageIcon("/src/Eye11.png"));
            txtSignUpPassword.setEchoChar('\u25cf');
            txtSignUpPassword.setText(con);
        }

    }//GEN-LAST:event_txtSignUpPasswordFocusLost

    private void txtCoinfirmCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCoinfirmCaretUpdate
        pwd=new String(txtCoinfirm.getPassword());
        btnCoinfirmEye.setEnabled(true);
        btnCoinfirmEye.setIcon(new ImageIcon("src/Eye11.png"));
        if (pwd.isEmpty()) {
            btnCoinfirmEye.setIcon(null);
            btnCoinfirmEye.setEnabled(false);
        }

    }//GEN-LAST:event_txtCoinfirmCaretUpdate

    private void btnCoinfirmEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoinfirmEyeMousePressed
        if (btnCoinfirmEye.isEnabled()) {
            //System.out.println("Button Pressed...");
            pwd = new String(txtCoinfirm.getPassword());
            txtCoinfirm.setEchoChar((char) 0);
            txtCoinfirm.setText(pwd);
            btnCoinfirmEye.setIcon(new ImageIcon("src/Eye12.png"));
        }

    }//GEN-LAST:event_btnCoinfirmEyeMousePressed

    private void btnCoinfirmEyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoinfirmEyeMouseReleased
        if (btnCoinfirmEye.isEnabled()) {
            //System.out.println("Button Released...");
            btnCoinfirmEye.setIcon(new ImageIcon("src/Eye11.png"));
            txtCoinfirm.setEchoChar('\u25cf');
            txtCoinfirm.setText(pwd);
        }

    }//GEN-LAST:event_btnCoinfirmEyeMouseReleased

    private void txtCoinfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCoinfirmFocusLost
    if(pwdValueCheck(pwd)){
        if(checkPass(pwd)){}
        else{
            JOptionPane.showMessageDialog(this,"Invalid Entry ,Please Write Atleast One Digit , Uppercase & LowerCase ","Error",0);
        }
    }
    else{
        JOptionPane.showMessageDialog(this,"Too Small","Error",0);
    }
    
        if (btnCoinfirmEye.isEnabled()) {
            //System.out.println("Button Released...");
            btnCoinfirmEye.setIcon(new ImageIcon("src/Eye11.png"));
            txtCoinfirm.setEchoChar('\u25cf');
            txtCoinfirm.setText(pwd);
        }
    
    }//GEN-LAST:event_txtCoinfirmFocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        con=new String(txtSignUpPassword.getPassword());
        pwd=new String(txtCoinfirm.getPassword());
        if(con.equals(pwd)){
        try
        {   
            stat.executeUpdate("insert into login values('"+txtFirstName.getText()+"','"+txtSignUpEmailId.getText()+"','"+con+"',"+txtMobile.getText()+");");
            if(rest.isClosed())
            {
            rest=stat.executeQuery("select * from login;");
            btnSignUpEye.doClick();
            }            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error "+e.getMessage());
        }
        }
        else{
            JOptionPane.showMessageDialog(this,"Password Doesn't Match","Error",0);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgImageSignUp;
    private javax.swing.JButton btnCoinfirmEye;
    private javax.swing.JButton btnSignUpEye;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel fgImageSignUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblImageSignUp;
    private javax.swing.JPasswordField txtCoinfirm;
    private javax.swing.JPanel txtCoinfirmPanel;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtSignUpEmailId;
    private javax.swing.JPanel txtSignUpPassPanel;
    private javax.swing.JPasswordField txtSignUpPassword;
    // End of variables declaration//GEN-END:variables
}
